# Generated by Django 5.2.16 on 2026-08-05 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scolarite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigurationSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='configuration/logo/', verbose_name='Logo du site')),
                ('image_visiteur', models.ImageField(blank=True, null=True, upload_to='configuration/visiteurs/', verbose_name='Image du visiteur')),
                ('image_utilisateur', models.ImageField(blank=True, null=True, upload_to='configuration/utilisateurs/', verbose_name="Image par défaut de l'utilisateur connecté")),
            ],
        ),
        migrations.AlterModelOptions(
            name='groupe',
            options={},
        ),
        migrations.AlterModelOptions(
            name='periode',
            options={},
        ),
        migrations.AlterField(
            model_name='periode',
            name='actif',
            field=models.BooleanField(default=True, help_text='Période en cours'),
        ),
        migrations.AlterField(
            model_name='periode',
            name='nom',
            field=models.CharField(help_text='Ex : Trimestre 1, Semestre 1 2025-2026', max_length=100),
        ),
    ]
