# Generated by Django 5.2.16 on 2026-08-06 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scolarite', '0002_configurationsite_alter_groupe_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='configurationsite',
            options={'verbose_name': 'Configuration du site', 'verbose_name_plural': 'Configuration du site'},
        ),
        migrations.AlterModelOptions(
            name='groupe',
            options={'ordering': ['nom'], 'verbose_name': 'Groupe', 'verbose_name_plural': 'Groupes'},
        ),
        migrations.AlterModelOptions(
            name='periode',
            options={'ordering': ['-date_debut', 'nom'], 'verbose_name': 'Période', 'verbose_name_plural': 'Périodes'},
        ),
        migrations.AddField(
            model_name='configurationsite',
            name='titre_site',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Titre du site'),
        ),
    ]
