# Generated by Django 5.2.16 on 2026-08-06 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scolarite', '0003_alter_configurationsite_options_alter_groupe_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(help_text='Ex : CM2, 6ème A, Terminale D', max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Classe',
                'verbose_name_plural': 'Classes',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Filiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(help_text='Ex : Génie Informatique, Droit privé', max_length=150, unique=True)),
            ],
            options={
                'verbose_name': 'Filière',
                'verbose_name_plural': 'Filières',
                'ordering': ['nom'],
            },
        ),
        migrations.AddField(
            model_name='periode',
            name='type_periode',
            field=models.CharField(blank=True, choices=[('trimestre', 'Trimestre (primaire / secondaire)'), ('semestre', 'Semestre (université)')], help_text='Trimestre (primaire/secondaire) ou Semestre (université).', max_length=10, null=True, verbose_name='Type de période'),
        ),
    ]
