# Generated by Django 5.2.16 on 2026-08-09 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cours', '0002_cours_classe_cours_filiere_cours_groupe_and_more'),
        ('scolarite', '0004_classe_filiere_periode_type_periode'),
    ]

    operations = [
        migrations.CreateModel(
            name='Etablissement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, max_length=200, verbose_name="Nom de l'établissement")),
                ('ville', models.CharField(blank=True, max_length=100, verbose_name='Ville')),
                ('quartier', models.CharField(blank=True, max_length=100, verbose_name='Quartier')),
                ('telephone', models.CharField(blank=True, max_length=20, verbose_name='Téléphone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('code_ou_decision', models.CharField(blank=True, help_text="Code d'ouverture / autorisation, ou numéro de décision ministérielle.", max_length=100, verbose_name='Code ou n° de décision')),
            ],
            options={
                'verbose_name': 'Établissement',
                'verbose_name_plural': 'Établissement',
            },
        ),
        migrations.AddField(
            model_name='periode',
            name='annee_scolaire',
            field=models.CharField(blank=True, help_text='Ex : 2025-2026', max_length=20, verbose_name='Année scolaire / académique'),
        ),
        migrations.CreateModel(
            name='Enseignant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_complet', models.CharField(max_length=200, verbose_name='Nom complet')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('telephone', models.CharField(blank=True, max_length=20, verbose_name='Téléphone')),
                ('classes', models.ManyToManyField(blank=True, related_name='enseignants', to='scolarite.classe', verbose_name='Classes en charge')),
                ('cours', models.ManyToManyField(blank=True, related_name='enseignants', to='cours.cours', verbose_name='Cours enseignés')),
            ],
            options={
                'verbose_name': 'Enseignant',
                'verbose_name_plural': 'Enseignants',
                'ordering': ['nom_complet'],
            },
        ),
    ]
