"""
Django settings for plateforme_exercices project.

Generated by 'django-admin startproject' using Django 6.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""
import os
from dotenv import load_dotenv
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv(BASE_DIR / '.env')
SECRET_KEY = os.getenv('SECRET_KEY')

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/



# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True
ALLOWED_HOSTS = ['localhost', '127.0.0.1', 'plateformesexercices.pythonanywhere.com']



SESSION_COOKIE_SECURE = False
CSRF_COOKIE_SECURE = False
SECURE_SSL_REDIRECT = False


# Dans plateforme_exercices/settings.py
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Apps du projet
    'comptes',
    'cours',
    'exercices',
    'devoirs',
    'scolarite',
    'rapports',
    'notifications',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'plateforme_exercices.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'scolarite.context_processors.configuration_site',
            ],
        },
    },
]

WSGI_APPLICATION = 'plateforme_exercices.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'fr-fr'

TIME_ZONE = 'Africa/Abidjan'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / "staticfiles"

# Fichiers uploadés par les utilisateurs (cours, devoirs, rendus...)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Redirections de connexion
LOGIN_URL = 'connexion'
LOGIN_REDIRECT_URL = 'tableau_de_bord'
LOGOUT_REDIRECT_URL = 'connexion'

# Taille max des fichiers uploadés (ex: vidéos de cours) : 200 Mo
DATA_UPLOAD_MAX_MEMORY_SIZE = 200 * 1024 * 1024
FILE_UPLOAD_MAX_MEMORY_SIZE = 200 * 1024 * 1024

# ============================================================
# Notifications - Email
# ============================================================
# Par defaut : les emails s'affichent dans la console (pratique en dev).
# Pour un envoi reel, decommente et complete le bloc SMTP ci-dessous
# (Gmail : active la validation en 2 etapes puis cree un "mot de passe
# d'application" sur https://myaccount.google.com/apppasswords).
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
# EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
# EMAIL_HOST = 'smtp.gmail.com'
# EMAIL_PORT = 587
# EMAIL_USE_TLS = True
# EMAIL_HOST_USER = 'ton_adresse@gmail.com'
# EMAIL_HOST_PASSWORD = 'mot_de_passe_application'
DEFAULT_FROM_EMAIL = 'no-reply@plateforme-exercices.local'

# ============================================================
# Notifications - SMS / WhatsApp (via Twilio)
# ============================================================
# Cree un compte gratuit sur https://www.twilio.com/try-twilio pour obtenir
# ACCOUNT_SID et AUTH_TOKEN. Pour WhatsApp, active le "WhatsApp Sandbox"
# (gratuit pour les tests) dans la console Twilio.
# Tant que ces valeurs sont vides, l'envoi de SMS/WhatsApp echouera proprement
# (erreur visible dans /admin/, l'email continue de fonctionner normalement).
TWILIO_ACCOUNT_SID = ''
TWILIO_AUTH_TOKEN = ''
TWILIO_SMS_FROM = ''        # numero Twilio achete pour l'envoi de SMS, ex: '+15017122661'
TWILIO_WHATSAPP_FROM = ''   # numero Twilio WhatsApp, ex: '+14155238886' (sandbox de test)
