# Generated by Django 6.0.7 on 2026-07-17 10:17

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cours', '0001_initial'),
        ('scolarite', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('type_exercice', models.CharField(choices=[('fixation', 'Exercice de fixation'), ('approfondissement', "Exercice d'approfondissement"), ('reflexion', 'Exercice de reflexion')], max_length=20)),
                ('coefficient', models.DecimalField(decimal_places=2, default=Decimal('1.00'), help_text='Coefficient utilise dans le calcul de la moyenne du bulletin.', max_digits=4)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('actif', models.BooleanField(default=True, help_text='Visible / accessible aux etudiants')),
                ('date_limite', models.DateTimeField(blank=True, null=True)),
                ('image_support', models.ImageField(blank=True, help_text="Image commune a l'exercice (ex: courbe, schema), affichee avant les questions.", null=True, upload_to='exercices/supports/%Y/%m/')),
                ('texte_support', models.TextField(blank=True, help_text="Texte de reference commun a l'exercice (ex: extrait litteraire a analyser), affiche avant les questions.")),
                ('matiere', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cours.matiere')),
                ('periode', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exercices', to='scolarite.periode')),
            ],
            options={
                'verbose_name': 'Exercice',
                'verbose_name_plural': 'Exercices',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_question', models.CharField(choices=[('qcm', 'QCM'), ('appariement', 'Appariement'), ('texte_trou', 'Texte a trous (closure)'), ('reponse_libre', 'Reponse libre / redaction (notee manuellement)')], max_length=20)),
                ('type_reponse_qcm', models.CharField(choices=[('unique', 'Une seule bonne reponse (boutons radio)'), ('multiple', 'Plusieurs bonnes reponses possibles (cases a cocher)')], default='unique', help_text='Uniquement utilise si le type de question est QCM.', max_length=10)),
                ('enonce', models.TextField(help_text='Pour un texte a trous, utiliser ___1___, ___2___, ... comme marqueurs de trou.')),
                ('image', models.ImageField(blank=True, help_text="Image illustrant l'enonce (schema, formule mathematique, graphique...).", null=True, upload_to='exercices/questions/%Y/%m/')),
                ('points', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=5)),
                ('ordre', models.PositiveIntegerField(default=0)),
                ('exercice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='exercices.exercice')),
            ],
            options={
                'verbose_name': 'Question',
                'verbose_name_plural': 'Questions',
                'ordering': ['ordre', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ElementAppariement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('element_gauche', models.CharField(blank=True, max_length=300)),
                ('image_gauche', models.ImageField(blank=True, help_text='Image a la place ou en plus du texte de gauche (ex: formule a associer).', null=True, upload_to='exercices/appariement/%Y/%m/')),
                ('element_droite', models.CharField(help_text='Correspondance correcte', max_length=300)),
                ('ordre', models.PositiveIntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paires', to='exercices.question')),
            ],
            options={
                'verbose_name': "Paire d'appariement",
                'verbose_name_plural': "Paires d'appariement",
                'ordering': ['ordre', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Choix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texte', models.CharField(blank=True, help_text='Peut rester vide si une image suffit.', max_length=300)),
                ('image', models.ImageField(blank=True, help_text='Image illustrant cette option (formule, schema...).', null=True, upload_to='exercices/choix/%Y/%m/')),
                ('est_correct', models.BooleanField(default=False)),
                ('ordre', models.PositiveIntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choix', to='exercices.question')),
            ],
            options={
                'verbose_name': 'Choix (QCM)',
                'verbose_name_plural': 'Choix (QCM)',
                'ordering': ['ordre', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TentativeExercice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateTimeField(auto_now_add=True)),
                ('date_soumission', models.DateTimeField(blank=True, null=True)),
                ('termine', models.BooleanField(default=False)),
                ('score_obtenu', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=6)),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tentatives', to=settings.AUTH_USER_MODEL)),
                ('exercice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tentatives', to='exercices.exercice')),
            ],
            options={
                'verbose_name': "Tentative d'exercice",
                'verbose_name_plural': "Tentatives d'exercice",
                'ordering': ['-date_debut'],
            },
        ),
        migrations.CreateModel(
            name='Trou',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(help_text='Numero du marqueur ___N___ correspondant')),
                ('reponses_acceptees', models.CharField(help_text="Reponse(s) correcte(s). Separer par '|' si plusieurs formulations sont acceptees.", max_length=300)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trous', to='exercices.question')),
            ],
            options={
                'verbose_name': 'Trou (texte a trous)',
                'verbose_name_plural': 'Trous (texte a trous)',
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='ReponseEtudiant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donnees_reponse', models.JSONField(blank=True, default=dict)),
                ('points_obtenus', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercices.question')),
                ('tentative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reponses', to='exercices.tentativeexercice')),
            ],
            options={
                'verbose_name': 'Reponse etudiant',
                'verbose_name_plural': 'Reponses etudiant',
                'unique_together': {('tentative', 'question')},
            },
        ),
    ]
