# Generated by Django 5.2.16 on 2026-08-08 06:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercices', '0001_initial'),
        ('scolarite', '0004_classe_filiere_periode_type_periode'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercice',
            name='classe',
            field=models.ForeignKey(blank=True, help_text='Pour organiser/filtrer (primaire / secondaire).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exercices', to='scolarite.classe', verbose_name='Classe'),
        ),
        migrations.AddField(
            model_name='exercice',
            name='filiere',
            field=models.ForeignKey(blank=True, help_text='Pour organiser/filtrer (université).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exercices', to='scolarite.filiere', verbose_name='Filière'),
        ),
        migrations.AddField(
            model_name='exercice',
            name='groupe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exercices', to='scolarite.groupe', verbose_name='Groupe'),
        ),
    ]
