# Generated by Django 6.0.7 on 2026-07-17 10:17

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scolarite', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Devoir',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('consignes', models.TextField(blank=True)),
                ('fichier_consigne', models.FileField(blank=True, null=True, upload_to='devoirs/consignes/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'doc', 'docx'])])),
                ('coefficient', models.DecimalField(decimal_places=2, default=Decimal('1.00'), help_text='Coefficient utilise dans le calcul de la moyenne du bulletin.', max_digits=4)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_limite', models.DateTimeField(blank=True, null=True)),
                ('actif', models.BooleanField(default=True)),
                ('periode', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devoirs', to='scolarite.periode')),
            ],
            options={
                'verbose_name': 'Devoir',
                'verbose_name_plural': 'Devoirs',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='RenduDevoir',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fichier', models.FileField(blank=True, null=True, upload_to='devoirs/rendus/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'doc', 'docx', 'py', 'jpg', 'jpeg', 'png'])])),
                ('texte_reponse', models.TextField(blank=True, help_text='Reponse redigee directement (optionnelle si un fichier est joint).')),
                ('commentaire_etudiant', models.TextField(blank=True)),
                ('date_soumission', models.DateTimeField(auto_now_add=True)),
                ('note', models.DecimalField(blank=True, decimal_places=2, help_text='Note sur 20 (utilisee telle quelle dans le calcul du bulletin).', max_digits=5, null=True)),
                ('commentaire_admin', models.TextField(blank=True)),
                ('fichier_correction', models.FileField(blank=True, null=True, upload_to='devoirs/corrections/%Y/%m/')),
                ('corrige', models.BooleanField(default=False)),
                ('devoir', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rendus', to='devoirs.devoir')),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rendus', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Rendu de devoir',
                'verbose_name_plural': 'Rendus de devoirs',
                'ordering': ['-date_soumission'],
                'unique_together': {('devoir', 'etudiant')},
            },
        ),
    ]
