# Generated by Django 5.2.16 on 2026-08-09 00:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cours', '0002_cours_classe_cours_filiere_cours_groupe_and_more'),
        ('devoirs', '0002_devoir_classe_devoir_filiere_devoir_groupe'),
    ]

    operations = [
        migrations.AddField(
            model_name='devoir',
            name='matiere',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devoirs', to='cours.matiere'),
        ),
    ]
