# Generated by Django 6.0.7 on 2026-07-10 21:37

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Matiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name': 'Matiere',
                'verbose_name_plural': 'Matieres',
            },
        ),
        migrations.CreateModel(
            name='Cours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('type_fichier', models.CharField(choices=[('pdf', 'PDF'), ('word', 'Document Word'), ('video', 'Video'), ('audio', 'Audio')], max_length=10)),
                ('fichier', models.FileField(upload_to='cours/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'doc', 'docx', 'mp4', 'mov', 'avi', 'mkv', 'mp3', 'wav', 'ogg', 'm4a'])])),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('visible', models.BooleanField(default=True, help_text='Visible par les etudiants')),
                ('matiere', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cours', to='cours.matiere')),
            ],
            options={
                'verbose_name': 'Cours',
                'verbose_name_plural': 'Cours',
                'ordering': ['-date_ajout'],
            },
        ),
    ]
