# Generated by Django 6.0.7 on 2026-07-17 10:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scolarite', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('etudiant', 'Etudiant'), ('admin', 'Administrateur / Enseignant')], default='etudiant', max_length=10)),
                ('classe', models.CharField(blank=True, help_text='Ex: L2 Info, Groupe A...', max_length=100)),
                ('numero_telephone', models.CharField(blank=True, help_text='Format international recommande, ex: +2250700000000 (necessaire pour SMS/WhatsApp).', max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('groupe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='etudiants', to='scolarite.groupe')),
                ('utilisateur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profil', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profil',
                'verbose_name_plural': 'Profils',
            },
        ),
    ]
