# Generated by Django 5.2.16 on 2026-08-06 21:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0001_initial'),
        ('cours', '0001_initial'),
        ('scolarite', '0003_alter_configurationsite_options_alter_groupe_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profil',
            name='cours',
            field=models.ManyToManyField(blank=True, help_text='Cours auxquels cet élève est inscrit.', related_name='etudiants', to='cours.cours', verbose_name='Cours suivis'),
        ),
        migrations.AddField(
            model_name='profil',
            name='periode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='etudiants', to='scolarite.periode', verbose_name='Période'),
        ),
    ]
