# Generated by Django 5.2.16 on 2026-08-09 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0003_profil_filiere_alter_profil_classe'),
    ]

    operations = [
        migrations.AddField(
            model_name='profil',
            name='avatar',
            field=models.ImageField(blank=True, help_text="Si aucune photo n'est ajoutée, l'avatar par défaut du site reste utilisé.", null=True, upload_to='comptes/avatars/%Y/%m/', verbose_name='Photo de profil'),
        ),
    ]
