# Generated by Django 6.0.7 on 2026-07-17 10:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scolarite', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objet', models.CharField(help_text="Utilise comme sujet pour l'email.", max_length=200)),
                ('message', models.TextField()),
                ('canal', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('whatsapp', 'WhatsApp')], default='email', max_length=10)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_envoi', models.DateTimeField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon (pas encore envoye)'), ('envoye', 'Envoye avec succes'), ('envoye_partiel', 'Envoye partiellement (voir le rapport)'), ('erreur', 'Echec total')], default='brouillon', max_length=20)),
                ('rapport_envoi', models.TextField(blank=True, help_text='Detail des envois reussis/echoues, rempli automatiquement.')),
                ('destinataires', models.ManyToManyField(blank=True, help_text='Selectionne directement des etudiants...', related_name='notifications_recues', to=settings.AUTH_USER_MODEL)),
                ('envoye_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('groupe_cible', models.ForeignKey(blank=True, help_text="...et/ou choisis un groupe entier (s'ajoute aux destinataires ci-dessus).", null=True, on_delete=django.db.models.deletion.SET_NULL, to='scolarite.groupe')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-date_creation'],
            },
        ),
    ]
